name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Log in to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Pull the pre-built Docker image from GitHub Container Registry
      - name: Pull Docker image
        run: |
          docker pull ghcr.io/voipplanner/battleship:latest

      # 4. Run tests (using dotnet test for .NET projects)
      - name: Run tests
        run: |
          docker run --rm ghcr.io/voipplanner/battleship:latest dotnet test /app/BattleShip.Api.Tests/BattleShip.Api.Tests.csproj

      # 5. Push the Docker image to GitHub Container Registry (optional)
      # If you want to push any changes back (e.g., after tests or updates)
      - name: Push Docker image (optional)
        run: |
          docker push ghcr.io/voipplanner/battleship:latest



