name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub token
          registry: ghcr.io  # Specify GitHub Container Registry (not Docker Hub)

      # 4. Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/voipplanner/battleship:latest .

      # 5. Run tests (using dotnet test for .NET projects)
      - name: Run tests
        run: |
          docker run --rm ghcr.io/voipplanner/battleship:latest dotnet test /app/BattleShip.Api.Tests/BattleShip.Api.Tests.csproj

      # 6. Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/voipplanner/battleship:latest

